name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Upload repo 
        uses: actions/upload-artifact@v2
          with: code
          path: .
      - name: Clone-down
        uses: actions/checkout@v2
      - name: my-step
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
     
